DEFINES		+= -D__ARM32_ARCH__=4

ASFLAGS		:= -Wall -O3
CFLAGS		:= -Wall -O3
LDFLAGS		:= -T arch/$(ARCH)/$(MACH)/user.lds -nostdlib

MCFLAGS		:= -std=gnu99 -O2 \
				-march=armv4t -mtune=arm920t \
				-ffreestanding -msoft-float -fsigned-char \
				-fno-omit-frame-pointer \
				-marm -mno-thumb-interwork

MASFLAGS	:= -D__ASSEMBLY__
MLDFLAGS	:=

LIBDIRS		:= -L $(dir $(shell $(CC) -march=armv4t -mtune=arm920t -print-libgcc-file-name))
LIBS		:= -lgcc
